### ISSUE TITLE
Fix Volunteer Reports sheet

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/org#103]
The Volunteer Reports sheet is missing some people that are on slack. Please compare the both the developer and business intake responses sheets to the volunteer reports sheet and add people that are missing. It should include everyone who has a #2 in the intake step column.

It is possible that the issue is that people are in slack who are not marked #2 so part of this task is to also go through the slack membership list and making sure everyone who is in slack has been fully onboarded (the email asking for answers to the additional questions was sent, there is a #2 in the intake process column, and they are on the volunteer reports sheet)

**Comment by GrfxGuru** [comment]
Rechecked the business intake responses sheet.

**Comment by GrfxGuru** [comment]
Initial repass of the intake response sheets. Now need to compare with Slack list and then check sheets are updated along with report.

**Comment by GrfxGuru** [comment]
Current slack user list checked against the volunteer report and added as needed.

**Comment by GrfxGuru** [comment]
Task completed.
