### ISSUE TITLE
Audit everyone on Slack

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/org#104]
Check the profiles for everyone on Slack. Anyone that does not have their profile set up properly should have the following message DM'd to them:

I see you have not filled in your slack profile as directed in the onboarding link. To me that indicates you may have not read the onboarding page. Can you please the link below and read through everything as required and also update your slack profile please. https://github.com/CodeDoesGood/org/wiki/2.-Onboarding

Star the DM's or keep a list or something...just keep track so that you can go back later and see if people replied to you and/or set up their profile. Anyone who has not replied and has also not set up their profile within 2 weeks should have an email sent to them. The email should say that we have sent them a message on Slack but have not heard from them, remind them that communication is supposed to take place through Slack and if they want to be a CDG volunteer they need to respond to messages there. In this email explain to them how they can make sure notifications are turned on, on Slack. After an email like this is saved, copy it to the Email Templates folder (inside the Recruiting folder) so that the same email can be used in the future.

**Comment by GrfxGuru** [comment]
Auditing has begun.

**Comment by GrfxGuru** [comment]
Those that have not completed their profiles have been sent a message.

**Comment by GrfxGuru** [comment]
Channels checked and those not in the correct channels have either been invited or asked to check that they join their platform (dev).
