### ISSUE TITLE
iPhone photo backup

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/org#114]
Need to figure out how to back up more than 4000 photos from one specific folder on an iPhone (not all the photos) over wifi (not using itunes on the computer). Needs to be a service that is easily browsable and prefer one that allows tagging of files.

**Comment by alidiafindley** [comment]
There are two ways to do this -- Google Drive and Dropbox. Google Drive provides 15GB of storage for free, compared to Dropbox's 2GB, making it the better choice for uploading this many images.

Here are the steps: 
1 - [Download Google Drive for iOS, here,](https://itunes.apple.com/us/app/google-drive-free-online-storage/id507874739?mt=8) on the iPhone being used.
2 - Log in to your account, or create one for free if you do not have one.
3 - Open the app, tap add, and tap upload.
4 - Browse to and choose the folder holding the images.
5 - Tap Upload.
6 - A progress bar will appear showing you the upload progress. This will likely take a while to upload -- I recommend doing it overnight or during a period while the phone isn't being heavily used.

[Here](https://support.google.com/drive/answer/2424368?co=GENIE.Platform%3DiOS&hl=en) is the official Google support page for this process.

If needed, more storage can be bought for Google Drive [here](https://www.google.com/settings/storage).

**Comment by abbeyjackson** [comment]
Thanks @alidiafindley !

**Comment by abbeyjackson** [comment]
@alidiafindley We tried to do this today but when we go into the folder you have to select the images one by one. Is there a way to select the entire folder?

**Comment by alidiafindley** [comment]
@abbeyjackson Submitted a [help request](https://productforums.google.com/forum/#!topic/drive/xRZvKVIWsvo;context-place=forum/drive) for this with Google Support. Will update as soon as I receive a response!

**Comment by abbeyjackson** [comment]
Thanks!

**Comment by alidiafindley** [comment]
@abbeyjackson  Google doesn't support uploading a whole folder to Drive from Camera Roll, so you'd have to select them individually. Apparently Dropbox and other similar softwares don't support this either. 

There is one app made as a workaround for this specific problem, but you have to pay for the iOS side. The computer side can be found [here for Mac](http://www.phototransferapp.com/mac/) or [here for PC](http://www.phototransferapp.com/desktop/); the iOS side can be found [here](https://itunes.apple.com/us/app/photo-transfer-app-easy-backup-of-photos-videos/id365152940?mt=8&ign-mpt=uo%3D4).

Here are the instruction guides with images [for Mac](http://www.phototransferapp.com/help/iphone/transfer_photos_from_your_iphone_or_itouch_to_your_mac/) and [for PC](http://www.phototransferapp.com/help/iphone/transfer_photos_from_your_iphone_or_itouch_to_your_pc/).
