### ISSUE TITLE
Add all volunteers to the announcement google group

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/org#118]
Add every single volunteer who has successfully onboarded to the announcements group on Google Drive. This group has no Google Drive access, this is so that we can send out a project wide email. At a later date we will not use email, it will only be through our software but right now we need a way to contact people. Email is not super reliable since we've noticed CDG emails end up in some people's spam but it will have to do in the meantime.

**Comment by abbeyjackson** [comment]
@GrfxGuru this needs to be done, remember you can give it to someone else on the team. Just make sure you update the assignee on this ticket if another person takes it on.

**Comment by GrfxGuru** [comment]
This task was taken care of by Emily. I would re-assign to her but do not seem to have GitHub details.
