### ISSUE TITLE
Find meeting time tool

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/org#132]
Research and find the simplest tool for finding a meeting time for a group of people. Example: people put in their availability and then the tool/website spits out a time that works for everyone.

**Comment by alidiafindley** [comment]
Looked around but couldn't find anything efficient that schedules a time without you putting in a list of time options to start. Let me know if that works -- if not, I'll give another option that doesn't require a starting list. 

The best way to do this is via [Doodle](http://doodle.com/). Here's how to use it:

1: Navigate to [the Doodle create page, here](http://doodle.com/create).
2: Enter a title, your name, and email. Location and description can be added as well, but are optional. Click next.
3: Select the date options. Once you've selected all the days, click next. 
4: For each day, enter the time options for that day. If people will be joining a call or video chat from different time zones, make sure to "Enable time zone support" via the blue link at the top. Click next.
5: Choose any relevant settings. Based on what you're looking for, I don't think any of these would be necessary -- except for perhaps the "Yes-No-Ifneedbe" setting, which adds an option for participants to mark a time as "if need be." Click next.
6: Choose a sharing setting. Then, you can choose to invite participants automatically by email, or to send them the link yourself. To invite them automatically by email: type the email address of the invitees in the box, separated by commas. You can choose to add a message which will appear in their invite email. If you are sending the link to them yourself, you can leave this box blank. Click finish.
7: You will receive two emails, one with an administrator's link, which allows you to change the settings if necessary; and one with the distribution link, which you can send out to the participants. If you chose to automatically send out invites via email, each participant will receive an email with a link to fill out the form. 
8: Once everyone fills out the form, a count at the bottom of each column will show you which is the most popular!

**Comment by abbeyjackson** [comment]
@alidiafindley thank you!
