### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/org#15]

**Comment by northtwilight** [comment]
**[Padlock](https://padlock.io)** for open source, cross-platform (Win/Mac/iOS/Android/Chrome extension, Linux coming soon) password management. Cloud-sync component, GPL3 license.
Passwords not to be shared on open channels under any circumstances.

**Comment by abbeyjackson** [comment]
unneeded (adding info to wiki directly)
