### ISSUE TITLE
Brainstorm name

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/org#29]
Sunday deadline

Please reply here with name ideas and on Sunday we will discuss
@renatomcamilio @northtwilight @98chimp

**Comment by renatomcamilio** [comment]
CSA: Cognitive Surplus Academy

**Comment by renatomcamilio** [comment]
Geeks United

**Comment by abbeyjackson** [comment]
ICU: International Coders United
THE: Technological Humanitarian Oraganization... then projects could be THE Hatchery
Spare Minds
GU: Geeks United, the GU Hatchery

**Comment by abbeyjackson** [comment]
Global Minds

**Comment by renatomcamilio** [comment]
THE: Technological Humanitarian Oraganization... then projects could be THE Hatchery
Spare Minds

**Comment by renatomcamilio** [comment]
GU: Geeks United, the GU Hatchery or Geek Hatchery

**Comment by renatomcamilio** [comment]
Global Coding for Change

**Comment by renatomcamilio** [comment]
PHD: Progressive Humanitarian Developers

**Comment by renatomcamilio** [comment]
Social Movement Coders

**Comment by abbeyjackson** [comment]
Global Coders
Coders United 
Coding Solutions

**Comment by abbeyjackson** [comment]
Coding For Change

**Comment by abbeyjackson** [comment]
Global Coding Consortium
Coding Mosaic
Programming Mosaic

**Comment by renatomcamilio** [comment]
UBC: United Beavelopers of Canada 🇨🇦

**Comment by renatomcamilio** [comment]
Social Resonance

**Comment by abbeyjackson** [comment]
When we did our first vote the top names were:

Geeks United
Coders United
Profusion
Unanimous
Coders Without Borders
Social Resonance
Unanimous World

**Comment by abbeyjackson** [comment]
I got three more names, two from devs who are interested in joining us and one from Justin:

Code Heroes
Me-nous
Bytes of Heart

**Comment by abbeyjackson** [comment]
@renatomcamilio @northtwilight @98chimp
