### ISSUE TITLE
Build Organization Wiki 

### ISSUE THREAD

**Issue by renatomcamilio** [CodeDoesGood/org#3]
The wiki will contain documents and plans for the organization. We are not sure about the access/permissions yet, but we may refer to internal/private docs from the Wiki, but not put sensitive info directly there.

**Comment by abbeyjackson** [comment]
To address the opening comments: Our wiki is on github and sensitive information will be kept in google docs.

**Comment by abbeyjackson** [comment]
Just an update, several pages are complete and are going through editing. About 25-30% of the wiki is done.

**Comment by abbeyjackson** [comment]
All organizational pages are done and I am now working through project specific information as we figure out how we want that to work.

**Comment by abbeyjackson** [comment]
I'm going to close this now @northtwilight and from here on we will make tickets for each page
