### ISSUE TITLE
Online Presence

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/org#31]
Twitter, Facebook, LinkedIn, reddit, instagram, snapchat (?), github, bitbucket (note some of these are already done)...  I can't think of anywhere else we should be.

Also just tacking this on here need to change the name in the logo so we are uploading the correct image.

@98chimp please post here the list of usernames and domains we have and also which email username is associated with them (you can do short form just username@unanimous so bots don't pull the email address out of this issue and spam) or put them in a google doc.

**Comment by 98chimp** [comment]
- [ ] Twitter
- [ ] Facebook
- [ ] LinkedIn
- [ ] reddit
- [ ] instagram
- [ ] snapchat
- [ ] github
- [ ] bitbucket

**Comment by renatomcamilio** [comment]
I've marked LinkedIn in the checklist as @abbeyjackson have already set one for us!

**Comment by abbeyjackson** [comment]
@northtwilight @98chimp @renatomcamilio We have a LinkedIn company page, feel free to add it to your LinkedIn. If you add it as volunteer experience it shows up on your profile under your name but it is way down the page so I added it as both volunteer and job experience.

<img width="506" alt="screen shot 2017-03-23 at 8 25 02 am" src="https://cloud.githubusercontent.com/assets/11657280/24255274/4647a668-0fa2-11e7-8a58-e896a4fb4a15.png">

**Comment by abbeyjackson** [comment]
Closing this ticket as we have registered on the major networks. @northtwilight has a list of credentials and is building a way for us to keep them organized.
