### ISSUE TITLE
Revise Logo

### ISSUE THREAD

**Issue by 98chimp** [CodeDoesGood/org#33]
Going to repurpose the existing logo so we can move forward quicker.

In due course, we may choose to change it.

**Comment by abbeyjackson** [comment]
@98chimp this is done, right?

**Comment by 98chimp** [comment]
right!

**Comment by abbeyjackson** [comment]
@98chimp Don't forget to move from InProgress to Done when you close an issue. I moved this one but FYI, closing a ticket doesn't automatically move it
