### ISSUE TITLE
DH Wiki - Chris

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/org#34]
All Hatchlings will be required to go through our onboarding. Onboarding will consist of reading specific articles about our processes and procedures, our purpose, etc. In addition to onboarding there will be training articles which Hatchlings are urged to read but will not necessarily be required. This issue will detail specific articles to be written.

This issue is for the pages that @cmyers78 is writing

- [ ] Holacracy / Distributed Authority
- [ ] Learning and Confidence

**Comment by abbeyjackson** [comment]
- [ ] Holacracy / Distributed Authority

**Comment by abbeyjackson** [comment]
@cmyers78 Hey Chris can we get a status update on this?

**Comment by cmyers78** [comment]
Sure.  I'm about finished my outline of material. There are a couple items I want to look into a bit further as I'm not coming up with good examples to relate to yet.    I will begin writing it up during my lunches this week.  

My outline is here: [https://docs.google.com/document/d/1fclceC8MLxjf8hPf2erRxoThHEF7J6czMl9q1fRl48Y/edit?usp=sharing](url)

**Comment by abbeyjackson** [comment]
@cmyers78 when you complete this can you please edit the link on this page:  https://github.com/CodeDoesGood/org/wiki/3.-Kanban-Procedures

just search the page for "Chris"

**Comment by abbeyjackson** [comment]
Assigned Shahin as reviewer

**Comment by abbeyjackson** [comment]
Forgot to add link:
https://github.com/CodeDoesGood/DevHatchery/wiki/Distributed-Authority

**Comment by cmyers78** [comment]
Ongoing task for multiple wiki articles

**Comment by cmyers78** [comment]
Began outline for Confidence Building & Impostor Syndrome - Time line to complete this article is Friday, 7 April

**Comment by cmyers78** [comment]
Revising section on Confidence Building and adding bridging sentence into Impostor Syndrome.

**Comment by cmyers78** [comment]
Have not gotten to start on Impostor Syndrome yet.  This is a light week of work so I should be able to work on it during my lunch hour.

**Comment by abbeyjackson** [comment]
Created separate issues for each article, closing this one
