### ISSUE TITLE
Revise the guiding principle about distributed authority

### ISSUE THREAD

**Issue by 98chimp** [CodeDoesGood/org#37]
1. Use our technical skills To Do Good.
2. Provide an avenue for new developers to be mentored.
3. Involvement is fun, rewarding, purposeful and easy.
4. Lower financial barriers for non-profits seeking software solutions.
5. Set an example for how distributed authority/decision-making (aka Holacracy*) can work. Every individual is autonomous, masterful and has a purpose.
6. Be guided by socially progressive ideals.
7. Be a volunteer-driven organization.
8. Strict procedures ensure efficient use of volunteer time.
9. Promote open source policies.

**Comment by abbeyjackson** [comment]
closing ticket as completed
