### ISSUE TITLE
Web Presence

### ISSUE THREAD

**Issue by renatomcamilio** [CodeDoesGood/org#4]
- [x] Simple website (or even a single page)
- [x] Contains about group info and small biographies for each of us
- [x] project portfolio
- [x] host on GitHub Pages
- [x] point the domain @98chimp holds to the GH Page

**Comment by abbeyjackson** [comment]
@renatomcamilio Let's go forward with a simple one page thing. We should have something online to identify ourselves to help with legitimacy and trust when contacting lawyers and orgs.

Do you have time / want to do that? @98chimp has the domain registered already.

**Comment by renatomcamilio** [comment]
Sure thing. I'll need a initial sketch, can be a paper & pen kind of thing, and I'm happy to put it together and setup everything.

**Comment by renatomcamilio** [comment]
Ok, updated the issue description with the TODO actions.

**Comment by abbeyjackson** [comment]
Just moving this into In Progress as I know you are working on it @renatomcamilio

**Comment by abbeyjackson** [comment]
@renatomcamilio As our web guy can you start thinking about how to turn our one web page into a full website that will represent us? You don't have to do the work alone, if you want volunteers let me know. If you need design ping Shahin.

**Comment by renatomcamilio** [comment]
@abbeyjackson for sure! I'll put together some alternatives to achieve that, and will ask for input from you guys based on a *pros & cons* sorta list.

**Comment by abbeyjackson** [comment]
Hey @renatomcamilio how is this coming? Is there anything anyone can help with?

**Comment by abbeyjackson** [comment]
As per the last meeting Renato is going to try to find a way to auto populate the website with info from the wiki and contributors from github contributor page.

Also we should have a "senior volunteers" section, in the same way we have a founders section where we can highlight volunteers that go above and beyond.

**Comment by renatomcamilio** [comment]
@abbeyjackson the scope of this task has changed since I've started. We started off with the landing page (which is live right now) - but it then grew into the full website with sections, and then also populating content from our wiki. I'll break down into cards that reflect that situation so we can track progress with more confidence.
