### ISSUE TITLE
DH Wiki- Ehsan

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/org#46]
All Hatchlings will be required to go through our onboarding. Onboarding will consist of reading specific articles about our processes and procedures, our purpose, etc. In addition to onboarding there will be training articles which Hatchlings are urged to read but will not necessarily be required. This issue will detail specific articles to be written.

This issue is for the pages that @ezaman is writing

[ ] Working at Home
[ ] MVC 
[ ] MVVM

**Comment by abbeyjackson** [comment]
@ezaman can I please get an update on these articles?

**Comment by ezaman** [comment]
Currently still working on MVVM article and making changes to MVC as well.

**Comment by ezaman** [comment]
Almost done, will upload all by end of weekend.

**Comment by abbeyjackson** [comment]
@ezaman fantastic! Thanks for keeping your ticket updated :)

**Comment by abbeyjackson** [comment]
Created separate issues for each article, closing this one
