### ISSUE TITLE
Volunteer Software Web design

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/org#53]
Volunteer software is outlined in Google Drive

**Comment by abbeyjackson** [comment]
@renatomcamilio will build the software

@98chimp is turning @abbeyjackson 's paper sketches to proper wireframes

**Comment by 98chimp** [comment]
[CDG_Volunteer_Site_01.pdf](https://github.com/CodeDoesGood/org/files/888727/CDG_Volunteer_Site_01.pdf)
[CDG_Volunteer_Site_02.pdf](https://github.com/CodeDoesGood/org/files/888730/CDG_Volunteer_Site_02.pdf)
[CDG_Volunteer_Site_03.pdf](https://github.com/CodeDoesGood/org/files/888729/CDG_Volunteer_Site_03.pdf)
[CDG_Volunteer_Site_04.pdf](https://github.com/CodeDoesGood/org/files/888731/CDG_Volunteer_Site_04.pdf)
[CDG_Volunteer_Site_05.pdf](https://github.com/CodeDoesGood/org/files/888733/CDG_Volunteer_Site_05.pdf)
[CDG_Volunteer_Site_06.pdf](https://github.com/CodeDoesGood/org/files/888732/CDG_Volunteer_Site_06.pdf)
[CDG_Volunteer_Site_07.pdf](https://github.com/CodeDoesGood/org/files/888728/CDG_Volunteer_Site_07.pdf)
[CDG_Volunteer_Site_08.pdf](https://github.com/CodeDoesGood/org/files/888734/CDG_Volunteer_Site_08.pdf)

**Comment by 98chimp** [comment]
all screens have now been digitized with a slight modification to fit the sketched content into the frame of a generic web browser

**Comment by renatomcamilio** [comment]
ty @98chimp!

**Comment by 98chimp** [comment]
@abbeyjackson when you get a chance, could you kindly take a peak at these PDFs. FYI, I left out the description notes with the intention of adding them back to the PDF using comments/annotations (which I will do early this week)

**Comment by renatomcamilio** [comment]
@98chimp @abbeyjackson I would like to bring up Zeplin (https://zeplin.io/); It's an amazing tool for this kind of collaborations (i.e. discussing over design, adding comments to screens, and it supports Sketch files import -- which would give layout specs info in a snap, pretty awesome)

**Comment by abbeyjackson** [comment]
@renatomcamilio @98chimp actually Shahin had earlier said we were going to be using Zeplin lol

Will check out the pdfs tonight :)

**Comment by renatomcamilio** [comment]
> @renatomcamilio @98chimp actually Shahin had earlier said we were going to be using Zeplin lol
that's awesome, guys!

**Comment by 98chimp** [comment]
i'll put the screens inside a Sketch project file and re-distribute through Zeplin

**Comment by abbeyjackson** [comment]
@98chimp great job getting these done! 

Changes needed:

- pdf 2, on New Project - Change "Not Interested" button to say "I'm Interested"
- pdf 4, not sure what do you think? Could we make the big text view span 2 columns? Have it under everything in the first column as well as the summary in the middle column? That way if it ends up being a 2 page scroll it won't be only 1/3 of the page used. Or even it could span all three columns under the image too...
- same idea with pd5 but instead of 3 columns make it two columns... everything in column 3 would be in column two then the project boxes would span two columns under the current column 1 material and the column 3 material (which would be in column 2)

Really like the layout changes you made to the profile (pdf 7), that looks way better than I had thought of!

**Comment by abbeyjackson** [comment]
As discussed at meeting and on Slack @renatomcamilio  will be making tickets for the software and deciding on technologies needed. At that point we will assign a team of volunteers to work on it.

**Comment by 98chimp** [comment]
wise decision
