### ISSUE TITLE
Find a social media volunteer

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/org#57]
We weren't planning to really do much with social media to start but messages are coming in and people are getting excited about us right off the bat. We need someone to take full ownership of the social media accounts. If they only want to man them for messages that is okay or they can post things also.

**Comment by felicelam** [comment]
Please let's discuss at our next meeting on 4/06.

**Comment by abbeyjackson** [comment]
We've got 3 or 4 people interested in social media, should be able to find someone from that group
