### ISSUE TITLE
Legal considerations of name

### ISSUE THREAD

**Issue by renatomcamilio** [CodeDoesGood/org#6]
- Look into legalities of using "without borders" moniker.
- If we use this name do we have to allow free entry? How do other groups handle this?

**Comment by renatomcamilio** [comment]
@abbeyjackson just to quote from Asana"
> From my brief research it should be okay as it does not appear to be trademarked however some groups have gone after each other for using similar names like Lawyers Without Borders and the Canadian based Lawyers Without Borders Canada. The original without borders is Doctors Without Borders France, it might be a good idea to reach out to them.

**Comment by abbeyjackson** [comment]
We also need to check about the group that calls themselves coders without borders:
http://cowobo.org/

At first glance they seem like a fully operational group but nothing on the website actually works
