### ISSUE TITLE
Visit the Enterprising Non-Profits of BC office (UBC downtown office; see note) for more resource

### ISSUE THREAD

**Issue by northtwilight** [CodeDoesGood/org#68]
https://sba.ubc.ca/bc-business-support-directory/enterprising-non-profits

(604) 871-5421
Contact Person: Kim Buksa, Program Coordinator
kim@enterprisingnonprofits.ca (link sends e-mail)
810 - 815 W. Hastings Street
Vancouver
British Columbia
V6C 1B4
http://www.enterprisingnonprofits.ca/

Will contact Monday or Tuesday depending on schedule

**Comment by REWMassimo** [comment]
No longer exists? Phone number doesn't route, email doesn't get delivered

**Comment by abbeyjackson** [comment]
The url enterprisingnonprofits.ca forwards to
http://vancitycommunityfoundation.ca/s/social_enterprise_development.asp

**Comment by abbeyjackson** [comment]
@REWMassimo This ticket is still listed as todo, is it complete?

**Comment by REWMassimo** [comment]
I'll close it, a different item is taking its place
