### ISSUE TITLE
Create Android Style guide

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/org#92]

**Comment by iamthepanda** [comment]
@wellingtonmb88 , how would you like to proceed?

**Comment by wellingtonmb88** [comment]
Estimated time to complete: 01/05/17

**Comment by abbeyjackson** [comment]
@wellingtonmb88 @iamthepanda Is the style guide complete now?

**Comment by iamthepanda** [comment]
@abbeyjackson I believe so.

**Comment by wellingtonmb88** [comment]
@abbeyjackson last week I asked in the Android channel for some reviews as nobody has said anything I believe it's completed, but I think the people could contribute later if it's necessary.

**Comment by abbeyjackson** [comment]
thanks guys! Could one of you please close the ticket (I'm replying through
email on my phone so I can't easily do it)
